# Generated by Django 4.1 on 2022-08-29 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ped', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
